# Generated by Django 4.2.6 on 2023-11-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfJefe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('edad', models.CharField(max_length=2)),
                ('asignatura', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=12)),
                ('correo', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=40)),
            ],
        ),
    ]
