# Generated by Django 4.2.6 on 2023-11-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfesorJefe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profjefe',
            name='edad',
            field=models.IntegerField(max_length=2),
        ),
    ]
